/* eslint-disable */
// WARNING: Do not edit this file

const ebconfig = {
  "integration": "react-1-T90R8bv-oqRNQibz64r8YPi9CtFDutzA7EDsIYZHpXwuyJPmD3WfyE--u9amALOWBQKfqw7fIM7M1olIXUcn6ihiVwkB77bUr00pwNGgBNArNn4mmHq5Zvz0",
  "tt": "tt-1-jWcUIqypquLuDnqbAD3Leh3C5L8ugvktlamreAV4DrU=",
  "version": "2020-11-20"
}

export default ebconfig;